const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
    UPDATE_CURRENT_URL: "UPDATE_CURRENT_URL",
    // //admin
    // ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    // ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    // PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAIL: 'REGISTER_USER_FAIL',
    SAVE_CHANGE_USER_SUCCESS: 'SAVE_CHANGE_USER_SUCCESS',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAIL: "DELETE_USER_FAIL",
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',

    //Customer
    GET_CUSTOMER_SUCCESS: 'GET_CUSTOMER_SUCCESS',
    GET_CUSTOMER_FAIL: 'GET_CUSTOMER_FAIL',
    CREATE_NEW_GUEST_SUCCESS: 'CREATE_NEW_GUEST_SUCCESS',

    //ADMIN
    GET_ALL_DATA: 'GET_ALL_DATA',
    CHANGE_ORDER_STATUS: 'CHANGE_ORDER_STATUS',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_TYPE_SUCCESS: 'UPDATE_PRODUCT_TYPE_SUCCESS',
    UPDATE_PRODUCT_DISCOUNT_SUCCESS: 'UPDATE_PRODUCT_DISCOUNT_SUCCESS',




    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',




    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    RELOAD_PRODUCT: "RELOAD_PRODUCT",
    SEARCH_PRODUCTS: 'SEARCH_PRODUCTS',
    SORT_PRODUCTS: 'SORT_PRODUCTS',
    FILTER_PRODUCTS: 'FILTER_PRODUCTS',
    GET_PRODUCT_INFO: 'GET_PRODUCT_INFO',


    SAVE_ORDER: 'SAVE_ORDER',
    CREATE_NEW_ORDER: 'CREATE_NEW_ORDER',
    GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
    CANCEL_ORDER: 'CANCEL_ORDER',

    FETCH_SHOPPING_CART_SUCCESS: "FETCH_SHOPPING_CART_SUCCESS",
    SAVE_CHANGE: "SAVE_CHANGE",
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_ITEM_CART: 'REMOVE_ITEM_CART',
    UPDATE_ITEM_CART: 'UPDATE_ITEM_CART',

    GET_NEW_NOTIFICATION: 'GET_NEW_NOTIFICATION',

})

export default actionTypes;